#Import Libraries and Files + Preprocessing

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# import required modules
import pandas as pd
import time

# time taken to read data
s_time = time.time()
url = "https://drive.google.com/file/d/1yaGl8vLBqKmz-ERNv5FoCfnZWIP7w_VX/view?usp=sharing"
df = pd.read_csv(url, quoting=3, sep = None,  error_bad_lines=False, engine='python', nrows=1000)
e_time = time.time()

print("Read without chunks:", (e_time - s_time), "seconds")

# Verify the DataFrame
print(df.head())

<ipython-input-3-0526cd8a2c8e>:8: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(url, quoting=3, sep = None,  error_bad_lines=False, engine='python', nrows=1000)

Read without chunks: 0.6715867519378662 seconds
  <!doctype html><html lang="en-US" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width  \
0                                            --c-tfs
1          ))*0.0625)*1rem);--wf-tfs-bp3:calc(((var(
2                                            --c-tfs
3          ))*0.0625)*1rem);--wf-tfs-bp5:calc(((var(
4                                            --c-tfs

   initial-scale=1"><style data-href="https://www.gstatic.com/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.RzbkUTW1gwA.L.X.O/am=hhwAITMeY4DyH0AACAAUKAAAAAAAAAAAAhkuIQ/d=1/ed=1/rs=AOaEmlHreNM4mwAMqhW8ZUYddR3uxy3KqQ/m=identifierview  \
0                                                 32
1                                               None
2                                                 36
3                                               None
4                                                 44

     _b  \
0  None
1  None
2  None
3  None
4  None

  _tp" nonce="MD7YTJD2uEmpB1xtcsD9lw">c-wiz{contain:style}c-wiz>c-data{display:none}c-wiz.rETSD{contain:none}c-wiz.Ubi8Z{contain:layout style}@-webkit-keyframes quantumWizBoxInkSpread{0%{-webkit-transform:translate(-50%  \
0                                               None
1                                               None
2                                               None
3                                               None
4                                               None

  -50%) scale(0.2);-webkit-transform:translate(-50%  \
0                                              None
1                                              None
2                                              None
3                                              None
4                                              None

  -50%) scale(0.2);-ms-transform:translate(-50%  \
0                                          None
1                                          None
2                                          None
3                                          None
4                                          None

  -50%) scale(0.2);-o-transform:translate(-50%  \
0                                         None
1                                         None
2                                         None
3                                         None
4                                         None

  -50%) scale(0.2);transform:translate(-50%  \
0                                      None
1                                      None
2                                      None
3                                      None
4                                      None

  -50%) scale(0.2)}to{-webkit-transform:translate(-50%  \
0                                               None
1                                               None
2                                               None
3                                               None
4                                               None

  -50%) scale(2.2);-webkit-transform:translate(-50%  ...  \
0                                              None  ...
1                                              None  ...
2                                              None  ...
3                                              None  ...
4                                              None  ...

  .BDEI9 button:not(.TrZEUc):focus::after  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN

  .BDEI9 button:not(.TrZEUc):active::after{background-color:rgba(26 115.7  \
0                                                NaN                  NaN
1                                                NaN                  NaN
2                                                NaN                  NaN
3                                                NaN                  NaN
4                                                NaN                  NaN

  232.3  \
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN

  0.15);-webkit-border-radius:2px;-moz-border-radius:2px;border-radius:2px;bottom:-2px;content:"";left:-3px;position:absolute;right:-3px;top:-2px;z-index:-1}.BDEI9 img:not(.TrZEUc){border:0;max-height:1.3em;vertical-align:middle}@media all and (min-width:601px){.BDEI9{display:-webkit-box;display:-moz-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-ms-flex-direction:column;-webkit-flex-direction:column;flex-direction:column;min-height:100vh;position:relative}.BDEI9:before  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  .BDEI9:after{-webkit-box-flex:1;box-flex:1;-ms-flex-positive:1;-webkit-flex-grow:1;flex-grow:1;content:"";height:24px}.BDEI9:before{min-height:30px}.BDEI9:after{min-height:24px}.BDEI9.LZgQXe:after{min-height:63.9996px}}.gEc4r{display:-webkit-box;display:-moz-box;display:-webkit-flex;display:-ms-flexbox;display:flex;height:24px;-webkit-justify-content:center;justify-content:center}.gEc4r.jlqJKb{height:auto;min-height:24px;padding-top:24px}.BivnM{-webkit-align-items:center;align-items:center;border-bottom:1px solid #ccc;display:-webkit-box;display:-moz-box;display:-webkit-flex;display:-ms-flexbox;display:flex;height:36px;left:0;padding:0 16px;position:absolute;right:0;top:0}.BivnM .ji6sFc{height:14px;margin-right:12px}.O3jdWc{color:rgb(95  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  99.2  \
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN

  104);font-size:14px;height:14px;margin-top:-2px}.Zwk8S{display:block;height:37px;width:37px}.wFNE4e{color:rgb(26  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  115.8 232)}:root{--wf-tfs:calc(((var(
0   NaN                             NaN
1   NaN                             NaN
2   NaN                             NaN
3   NaN                             NaN
4   NaN                             NaN

[5 rows x 180 columns]

Skipping line 24: Expected 180 fields in line 24, saw 5357
Skipping line 40: Expected 180 fields in line 40, saw 394
Skipping line 42: Expected 180 fields in line 42, saw 273
Skipping line 43: Expected 180 fields in line 43, saw 3083

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [ ]:
# Import GEE Features in DF
columns_to_extract = ["new_ind", "index", "ADM1DHS", "ADM1FIPS","ADM1FIPSNA", "ADM1NAME", "ADM1SALBCO", "ADM1SALBNA", "ADM1SALNA", "ALT_DEM", "ALT_GPS", "CCFIPS", "DATUM", "DHSCC", "DHSCLUST", "DHSID", "DHSREGCO", "DHSREGNA", "DHSYEAR", "F21", "F22", "F23", "LATNUM", "LONGNUM", "SOURCE", "URBAN_RURA", "ZONECO", "ZONENA"]
df=pd.read_csv("/content/drive/MyDrive/gee_features.csv",usecols=columns_to_extract)

<ipython-input-5-6a2e0eb81ff0>:2: DtypeWarning: Columns (3,4,5,6,7,11,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/gee_features.csv",usecols=columns_to_extract)

In [ ]:
id_file=pd.read_csv("/content/drive/MyDrive/training_label.csv")

In [ ]:
id_file.columns

Index(['DHSID', 'DHSYEAR', 'DHSCLUST', 'LATNUM', 'LONGNUM', 'Mean_BMI',
       'Median_BMI', 'Unmet_Need_Rate', 'Under5_Mortality_Rate',
       'Skilled_Birth_Attendant_Rate', 'Stunted_Rate', 'URBAN_RURA'],
      dtype='object')

In [ ]:
id=df[df["DHSID"].isin(id_file["DHSID"])]

In [ ]:
id.set_index("DHSID",inplace=True)
# id_y.set_index(id_y.Index([0]), inplace = True)
id

In [ ]:
df.isnull().sum()
# df.dtypes

In [ ]:
# !pip install pandas-profiling

In [ ]:
# from pandas_profiling import ProfileReport
# profile=ProfileReport(df)
# profile.to_file(output_file="output.html")

In [ ]:
columns_to_drop = ["ZONECO", "ZONENA"]
df = df.drop(columns=columns_to_drop)

In [ ]:
columns_to_drop = ["F21","F22","F23","ADM1SALNA"]
df = df.drop(columns=columns_to_drop)

In [ ]:
df.head()

,new_ind,index,ADM1DHS,ADM1FIPS,ADM1FIPSNA,ADM1NAME,ADM1SALBCO,ADM1SALBNA,ALT_DEM,ALT_GPS,...,DHSCC,DHSCLUST,DHSID,DHSREGCO,DHSREGNA,DHSYEAR,LATNUM,LONGNUM,SOURCE,URBAN_RURA
0,AL_2008_00000001,0,9999,NaN,NaN,NaN,NaN,NaN,45.0,39.0,...,AL,1,AL200800000001,2,central,2008,40.822650,19.838322,GPS,R
1,AL_2008_00000002,40,9999,NaN,NaN,NaN,NaN,NaN,65.0,92.0,...,AL,2,AL200800000002,2,central,2008,40.696846,20.007555,GPS,R
2,AL_2008_00000003,80,9999,NaN,NaN,NaN,NaN,NaN,261.0,41.0,...,AL,3,AL200800000003,2,central,2008,40.750040,19.974262,GPS,R
3,AL_2008_00000004,120,9999,NaN,NaN,NaN,NaN,NaN,29.0,22.0,...,AL,4,AL200800000004,2,central,2008,40.798930,19.863338,GPS,R
4,AL_2008_00000005,160,9999,NaN,NaN,NaN,NaN,NaN,130.0,47.0,...,AL,5,AL200800000005,2,central,2008,40.746124,19.843885,GPS,R

In [ ]:
# Convert the categorical data into numerical data
df['DHSREGNA']= df['DHSREGNA'].astype('category')
df['URBAN_RURA']= df['URBAN_RURA'].astype('category')
df['SOURCE']= df['SOURCE'].astype('category')
df['ADM1NAME']= df['ADM1NAME'].astype('category')
df['DHSREGNA'] = df['DHSREGNA'].cat.codes
df['URBAN_RURA'] = df['URBAN_RURA'].cat.codes
df['SOURCE'] = df['SOURCE'].cat.codes
df['ADM1NAME'] = df['ADM1NAME'].cat.codes
df[['URBAN_RURA','DHSREGNA','SOURCE']].head()

   URBAN_RURA  DHSREGNA  SOURCE
0           0      1254       2
1           0      1254       2
2           0      1254       2
3           0      1254       2
4           0      1254       2

In [ ]:
# Normalize the numerical data values

df['DHSREGNA'] = df['DHSREGNA'] /df['DHSREGNA'].abs().max()
df['DHSYEAR'] = df['DHSYEAR'] - df['DHSYEAR'].mean()
df['ADM1DHS'] = df['ADM1DHS'] /df['ADM1DHS'].abs().max()
df['ALT_DEM'] = df['ALT_DEM'] /df['ALT_DEM'].abs().max()
df['ALT_GPS'] = df['ALT_GPS'] /df['ALT_GPS'].abs().max()

In [ ]:
# Create a new column that creates a country code from the DHSID that can be used for grouping
df['ID'] = df["DHSID"].str.slice(0, 2)
df['ID']= df['ID'].astype('category')
df['ID'] = df['ID'].cat.codes
df.head()

,new_ind,index,ADM1DHS,ADM1FIPS,ADM1FIPSNA,ADM1NAME,ADM1SALBCO,ADM1SALBNA,ALT_DEM,ALT_GPS,...,DHSCLUST,DHSID,DHSREGCO,DHSREGNA,DHSYEAR,LATNUM,LONGNUM,SOURCE,URBAN_RURA,ID
0,AL_2008_00000001,0,0.97761,NaN,NaN,-1,NaN,NaN,0.004500,0.000801,...,1,AL200800000001,2,0.770744,-1.884142,40.822650,19.838322,2,0,0
1,AL_2008_00000002,40,0.97761,NaN,NaN,-1,NaN,NaN,0.006501,0.001889,...,2,AL200800000002,2,0.770744,-1.884142,40.696846,20.007555,2,0,0
2,AL_2008_00000003,80,0.97761,NaN,NaN,-1,NaN,NaN,0.026103,0.000842,...,3,AL200800000003,2,0.770744,-1.884142,40.750040,19.974262,2,0,0
3,AL_2008_00000004,120,0.97761,NaN,NaN,-1,NaN,NaN,0.002900,0.000452,...,4,AL200800000004,2,0.770744,-1.884142,40.798930,19.863338,2,0,0
4,AL_2008_00000005,160,0.97761,NaN,NaN,-1,NaN,NaN,0.013001,0.000965,...,5,AL200800000005,2,0.770744,-1.884142,40.746124,19.843885,2,0,0

In [ ]:
# Save processed dataframe

df.to_csv("/content/drive/MyDrive/Stanford Predictions/Dataframe.csv",index=True)

In [ ]:
# Load The Training label

train_df=pd.read_csv("/content/drive/MyDrive/training_label.csv", sep=r'\s*,\s*',header=0, encoding='ascii', engine='python')

In [ ]:
# Merge the training dataset and the gee features based on DHSID

merge_df=df.merge(train_df,on
                  ="DHSID",how="outer")

In [ ]:
merge_df.isnull().sum()

In [ ]:
merge_df

In [ ]:
# Create a new country code column
merge_df['ID'] = merge_df["DHSID"].str.slice(0, 2)
merge_df

,new_ind,index,ADM1DHS,ADM1FIPS,ADM1FIPSNA,ADM1NAME,ADM1SALBCO,ADM1SALBNA,ALT_DEM,ALT_GPS,...,DHSCLUST_y,LATNUM_y,LONGNUM_y,Mean_BMI,Median_BMI,Unmet_Need_Rate,Under5_Mortality_Rate,Skilled_Birth_Attendant_Rate,Stunted_Rate,URBAN_RURA_y
0,AL_2008_00000001,0.0,0.97761,NaN,NaN,-1.0,NaN,NaN,0.004500,0.000801,...,1.0,40.822652,19.838321,24.12,25.28,50.00,9.68,100.00,20.0,R
1,AL_2008_00000002,40.0,0.97761,NaN,NaN,-1.0,NaN,NaN,0.006501,0.001889,...,2.0,40.696846,20.007555,23.04,21.98,7.69,8.33,66.67,0.0,R
2,AL_2008_00000003,80.0,0.97761,NaN,NaN,-1.0,NaN,NaN,0.026103,0.000842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AL_2008_00000004,120.0,0.97761,NaN,NaN,-1.0,NaN,NaN,0.002900,0.000452,...,4.0,40.798931,19.863338,26.74,26.57,7.69,2.86,100.00,0.0,R
4,AL_2008_00000005,160.0,0.97761,NaN,NaN,-1.0,NaN,NaN,0.013001,0.000965,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30828.0,27.408811,93.764485,22.25,21.10,100.00,NaN,NaN,NaN,R
121882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30829.0,27.685279,93.597370,22.14,22.03,0.00,NaN,NaN,NaN,R
121883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30830.0,27.105265,93.633651,22.54,22.74,66.67,NaN,NaN,NaN,U
121884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30832.0,28.142182,95.846006,22.82,23.78,33.33,NaN,NaN,NaN,U
121885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30833.0,28.668374,96.008550,25.24,25.20,33.33,NaN,NaN,NaN,R

In [ ]:
df_filled=merge_df[['DHSID', 'ADM1DHS', 'ALT_DEM', 'ALT_GPS', 'ADM1NAME', 'DHSREGNA', 'DHSYEAR_x', 'URBAN_RURA_x', 'SOURCE', 'LATNUM_y', 'LONGNUM_y', "DHSCLUST_x",'DHSREGCO', 'ID', 'Mean_BMI', 'Median_BMI', 'Unmet_Need_Rate', 'Under5_Mortality_Rate', 'Skilled_Birth_Attendant_Rate', 'Stunted_Rate']]

In [ ]:
# Mean values grouped by country code to fill NA Values

mean_vals = df_filled.groupby(['ID']).mean()
mean_vals
# df_filled

<ipython-input-32-bc4cecfe9391>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mean_vals = df_filled.groupby(['ID']).mean()

,ADM1DHS,ALT_DEM,ALT_GPS,ADM1NAME,DHSREGNA,DHSYEAR_x,URBAN_RURA_x,SOURCE,LATNUM_y,LONGNUM_y,DHSCLUST_x,DHSREGCO,Mean_BMI,Median_BMI,Unmet_Need_Rate,Under5_Mortality_Rate,Skilled_Birth_Attendant_Rate,Stunted_Rate
ID,,,,,,,,,,,,,,,,,,
AL,0.378017,0.025907,0.004961,280.989700,0.546782,3.639463,0.522747,1.986266,41.210404,19.947645,3.068197e+02,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
AM,0.977610,0.130040,0.027042,-1.000000,0.648438,2.635987,0.665056,1.877617,40.260384,44.723831,1.557601e+02,5.996779,25.431356,24.621907,20.118435,2.428842,99.897557,17.133840
AO,0.000899,0.081945,0.205285,400.502400,0.307234,5.115858,0.552000,1.980800,-10.718080,15.586064,3.138384e+02,9.195200,NaN,NaN,80.686875,8.652272,48.424176,36.197504
BD,0.000363,0.002955,0.151129,550.698188,0.492767,-1.501022,0.339814,1.981441,23.828502,90.042784,2.624401e+02,3.716748,21.614456,21.277443,19.366729,10.626827,28.934954,37.396413
BF,0.979339,0.057164,0.082759,-1.000000,0.457776,-6.064891,0.343130,1.839824,11.993389,-1.903531,2.114416e+02,6.012491,21.049277,20.775871,60.175302,16.861883,39.332427,33.191939
BJ,0.000562,0.026114,0.145233,473.881279,0.331187,0.322479,0.440068,2.002283,7.785246,2.237399,3.937875e+06,5.978311,23.034853,22.453681,63.764587,11.956933,81.300244,40.261264
BO,0.000431,0.229132,0.205285,1133.118000,0.869352,-1.884142,0.593000,2.002000,-17.681087,-65.718719,4.472548e+03,4.406000,25.789230,25.105406,23.362143,8.760406,78.852713,22.980923
BU,0.395806,0.151924,0.100761,260.600000,0.363574,3.690052,0.194624,2.002151,-3.285360,29.782965,2.415172e+02,6.978495,20.982833,20.734855,55.686777,11.056175,76.686280,53.581642
CD,0.002608,0.128563,0.138859,501.111244,0.324724,0.962748,0.342105,2.004785,-3.276298,21.011760,2.271998e+02,21.956938,21.545640,21.251128,60.400771,12.615424,68.625441,45.127404
CF,0.977610,0.051726,0.205285,-1.000000,0.897062,-15.884142,0.467532,1.000000,5.389590,18.839173,3.770173e+02,3.571429,NaN,NaN,50.927982,14.949870,46.588826,NaN
CI,0.651473,0.033479,0.205285,383.488467,0.661751,-6.551713,0.550882,1.938942,6.708787,-5.093570,1.449430e+02,4.131615,22.848311,22.410686,53.767358,12.750079,62.407681,28.581250
CM,0.090300,0.066312,0.150342,608.104744,0.556619,-0.875516,0.527418,1.911275,5.690904,11.630389,2.405946e+02,6.078866,23.866437,23.379312,48.631211,11.224587,72.690188,27.285769
CO,0.004607,0.113788,0.023438,1086.870664,0.837418,0.115858,0.701223,1.933226,5.297267,-72.722643,2.502632e+03,3.227792,25.036915,24.551342,9.032654,2.587232,93.289636,12.117227
DH,0.977610,0.001707,0.005369,438.286798,0.327857,8.115858,0.335357,2.000000,24.028709,90.169115,3.343869e+02,4.394537,23.289874,22.976779,14.891516,7.362674,55.242232,30.564884
DR,0.179841,0.016966,0.173492,928.583286,0.721176,-1.788549,0.578134,1.952490,18.862208,-70.254962,1.662137e+03,3.704637,25.810457,25.232087,13.166062,4.442216,79.502121,9.629308
EG,0.310176,0.123263,0.171567,446.099809,0.542994,-5.364193,0.478394,1.997578,28.807059,30.720964,2.588572e+06,3.237476,30.416870,30.150280,19.832128,7.751292,75.211396,24.782383
ET,0.000665,0.194135,0.166349,723.985300,0.692713,-1.702992,0.289235,1.511457,9.375167,38.005088,2.996485e+02,6.469952,20.117141,19.853680,59.613158,13.896250,15.729504,36.397378
GA,0.157531,0.033700,0.006922,516.747024,0.450672,2.115858,0.544643,2.011905,-0.693167,10.826659,1.685000e+02,5.241071,24.515776,23.782802,50.428319,6.556862,78.016891,21.106624
GH,0.000516,0.022247,0.176704,544.545085,0.494952,-2.358040,0.449492,1.864746,6.929789,-1.043768,2.803563e+02,5.279322,23.393463,22.839259,56.681291,10.554181,60.240980,22.520615
GN,0.222556,0.045470,0.099833,455.943367,0.531223,-0.574599,0.356866,2.000776,10.155346,-11.744298,8.644919e+02,3.800621,22.270865,21.875293,72.296371,15.374647,36.810843,29.906188
GU,0.001042,0.121222,0.205285,458.738928,0.498575,5.115858,0.446387,2.005828,14.765031,-89.981950,4.338240e+02,4.343823,26.055598,25.608837,19.100648,4.409917,74.996483,38.022150
GY,0.000502,0.045199,0.205285,419.150769,0.926394,-0.884142,0.273846,1.953846,6.032767,-55.821687,1.650123e+02,5.135385,25.934402,25.436624,38.068638,4.354213,89.852478,17.817930
HN,0.000888,0.074483,0.019769,394.302265,0.374664,1.115858,0.438153,2.016551,14.509591,-86.083342,5.760261e+02,11.692509,25.844357,25.218703,13.211271,3.659498,83.502247,21.609716
HT,0.215015,0.034346,0.164478,540.519639,0.547773,-0.491997,0.406310,1.989053,18.659133,-71.768227,1.990193e+02,4.969736,22.429649,21.786690,54.390109,10.865293,33.914684,20.821653
IA,0.002036,0.042850,0.196372,546.511012,0.364286,4.115858,0.298490,1.887864,23.564581,81.012480,2.091782e+05,309.870922,21.838469,21.365519,25.672097,NaN,NaN,NaN
ID,0.003989,0.066938,0.014904,1110.561782,0.857205,-6.884142,0.425287,2.052443,-3.879891,105.101015,4.100187e+07,40.795977,NaN,NaN,14.157163,7.161467,45.942588,NaN
JO,0.219576,0.305374,0.084350,302.935542,0.579958,-2.194795,0.699194,1.587735,31.538858,35.666277,3.949808e+02,1.892569,30.248206,29.994140,18.287383,2.993617,98.936985,11.095882
KE,0.003425,0.137992,0.205285,643.344900,0.478951,1.278066,0.367057,0.681856,-0.449672,36.574453,6.040987e+02,4.499582,23.103839,22.679853,33.223046,7.107693,58.391600,26.761257
KH,0.508014,0.010206,0.155463,547.645778,0.870845,-2.129031,0.271111,0.714667,12.105022,104.049392,2.846627e+02,9.758667,21.188435,20.866260,36.466759,9.529414,52.506755,37.201108
KM,0.000229,0.057938,0.205285,647.896825,0.472530,2.115858,0.428571,1.940476,-11.363921,41.527788,1.265000e+02,2.337302,23.699425,22.976839,61.621494,4.630000,86.116034,27.273851
LB,0.572283,0.023740,0.050287,195.935567,0.691090,-4.616100,0.369845,1.759021,6.265544,-9.522308,1.843209e+02,3.157216,22.856446,22.233676,67.715909,17.294843,54.649258,34.588254
LS,0.000515,0.378939,0.205285,932.592193,0.717103,-0.909059,0.266611,0.702658,-28.722567,27.283477,2.013048e+02,4.186877,24.929595,24.295171,32.339746,8.780132,67.368502,34.928554
MA,0.000930,0.043916,0.205285,555.454167,0.877013,-6.884142,0.564583,2.000000,33.104927,-6.627387,2.405000e+02,9.510417,23.889625,23.245083,13.811479,7.613708,69.039917,NaN
MB,0.977610,0.013907,0.002767,-1.000000,0.841211,-4.884142,0.582500,2.002500,47.059012,28.397920,2.005000e+02,2.487500,25.289800,24.204175,9.846400,3.082500,99.826693,NaN
MD,0.002345,0.071590,0.074225,509.038239,0.387595,-5.312879,0.298957,2.009270,-18.885919,46.723069,2.480313e+02,23.982619,20.376796,20.135789,44.048646,10.906104,54.091441,47.403417
ML,0.000423,0.042555,0.044285,616.624531,0.469824,-3.022867,0.328870,1.983931,13.437599,-6.199288,2.111521e+02,4.325656,22.319247,21.827725,74.277444,17.968040,38.547969,33.495484
MM,0.000797,0.025326,0.005182,535.247166,0.404194,5.115858,0.276644,1.979592,19.520986,96.202509,2.210113e+02,8.147392,22.355818,21.756195,26.807830,8.808333,74.713438,27.678038
MW,0.380280,0.091761,0.147762,347.971942,0.656489,-1.494214,0.182374,1.411151,-14.082462,34.301768,8.007367e+02,73.970863,22.202323,21.830657,38.426277,14.572517,70.170582,41.127800
MZ,0.000589,0.029487,0.205285,581.672283,0.446544,1.695471,0.431340,1.500421,-19.307429,35.290653,2.280767e+02,6.021061,22.603174,22.089521,55.572687,8.171314,72.051973,36.801955
NG,0.180045,0.038250,0.186548,490.443748,0.560036,1.038333,0.397807,1.932394,8.335231,7.152673,5.769974e+02,3.368050,22.807877,22.118277,58.821353,13.192044,52.686362,34.445811
NI,0.521096,0.031921,0.205285,556.534791,0.912813,-14.687323,0.387674,1.471173,13.880447,5.341063,1.267913e+02,4.186879,NaN,NaN,70.784274,24.416103,30.581828,NaN
NM,0.000682,0.115763,0.139342,653.293893,0.413566,-2.136050,0.447328,1.167176,-20.358410,17.158579,2.378756e+02,6.086260,23.767551,23.073660,21.139306,5.927444,83.793962,23.123721
NP,0.000301,0.079552,0.016652,829.987320,0.605227,-0.486001,0.390533,2.000000,27.807280,84.264057,2.525101e+03,2.459003,21.359656,21.016197,36.011141,9.817519,39.818022,38.817283
PE,0.001286,0.154002,0.067900,959.581317,0.786915,-5.883397,0.598809,1.609602,-10.753268,-75.251265,6.777992e+02,10.900819,25.259545,24.790286,11.532133,6.615229,65.819421,23.106105
PH,0.000968,0.026313,0.157649,831.630549,0.634637,0.616732,0.451590,1.407200,11.880312,120.779140,5.005876e+02,9.903880,NaN,NaN,27.324658,3.673462,73.111962,100.000000
PK,0.280814,0.397824,0.205285,375.050881,0.627558,0.141299,0.437704,1.743640,30.151944,70.207688,4.148813e+02,2.546641,25.822410,25.364154,46.587966,8.742843,51.313026,35.693608
RW,0.000304,0.177078,0.156059,704.088496,0.587921,-0.379717,0.215339,1.424779,-2.000977,29.639532,2.245965e+02,17.207670,22.163333,21.988298,44.051957,12.700043,60.890684,40.219350
SL,0.000255,0.030085,0.122633,647.736804,0.426661,4.355594,0.379032,1.502199,8.285753,-11.856313,2.376796e+02,22.198680,23.276511,22.760093,55.638959,14.736862,70.322659,33.916267
SN,0.260528,0.012401,0.140900,512.000000,0.705199,-3.046590,0.397147,1.693971,14.215974,-15.534508,1.468495e+02,3.923148,21.707452,21.132357,67.625115,11.813671,57.301889,22.271676
SZ,0.000236,0.086347,0.017809,1037.607273,0.796158,-3.884142,0.403636,2.018182,-25.981358,30.783114,1.380000e+02,2.410909,26.453918,25.505000,24.549072,8.000670,78.371237,26.300000
TD,0.001098,0.041901,0.205285,503.434295,0.375411,4.115858,0.261218,1.923077,12.140723,17.643215,3.130481e+02,11.229167,20.970046,20.627945,86.316736,12.902662,24.426018,42.736525
TG,0.194216,0.021016,0.044474,421.005188,0.566468,-7.448344,0.425422,1.796368,7.882599,1.041137,1.795435e+02,3.038911,23.354792,22.740292,51.652852,12.222245,55.036408,26.825902
TJ,0.000291,0.114404,0.205285,411.875346,0.324656,4.650484,0.457064,2.013850,37.758562,67.909671,1.810346e+02,2.972299,23.940361,23.046733,44.003213,4.712108,86.879618,20.923219
TL,0.000681,0.050562,0.107782,707.760440,0.546662,2.615858,0.269231,1.003297,-8.806832,125.476133,2.280000e+02,6.968132,20.263838,19.960078,55.517672,7.319251,42.955445,51.838612
TZ,0.001779,0.090774,0.205285,536.149671,0.480734,5.115858,0.296053,1.983553,-5.877235,35.774304,3.045000e+02,5.547697,23.401478,22.681963,38.889169,8.571524,13.549630,32.562593
UG,0.681301,0.152815,0.126490,134.627013,0.484900,0.173103,0.240161,2.018784,0.931123,31.178555,5.211096e+02,5.339445,22.337721,21.982248,49.982520,11.750686,55.043825,32.607883
UZ,0.977610,0.044187,0.011789,-1.000000,0.866339,-7.884142,0.461187,2.004566,NaN,NaN,2.633425e+02,3.063927,NaN,NaN,NaN,NaN,NaN,NaN
ZA,0.000492,0.095114,0.205285,503.664879,0.391559,7.115858,0.621984,2.000000,-28.477548,26.811445,3.757708e+02,5.033512,28.476500,27.892580,21.116332,4.026973,96.761523,23.398481
ZM,0.000524,0.119152,0.060285,604.395490,0.757097,3.467550,0.400694,1.962272,-13.109864,28.355867,3.129545e+02,5.362533,22.221429,21.694873,34.893810,9.616695,68.954874,37.700448
ZW,0.000515,0.372793,0.154930,495.828452,0.723023,-1.641464,0.381450,2.000697,-18.496722,29.793360,3.030112e+02,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275

In [ ]:
mean_vals.reset_index(inplace=True)
merged_vals = df_filled.merge(mean_vals, on='ID', how='outer')
merged_vals

,DHSID,ADM1DHS_x,ALT_DEM_x,ALT_GPS_x,ADM1NAME_x,DHSREGNA_x,DHSYEAR_x_x,URBAN_RURA_x_x,SOURCE_x,LATNUM_y_x,...,LATNUM_y_y,LONGNUM_y_y,DHSCLUST_x_y,DHSREGCO_y,Mean_BMI_y,Median_BMI_y,Unmet_Need_Rate_y,Under5_Mortality_Rate_y,Skilled_Birth_Attendant_Rate_y,Stunted_Rate_y
0,AL200800000001,0.977610,0.004500,0.000801,-1.0,0.770744,-1.884142,0.0,2.0,40.822652,...,41.210404,19.947645,306.819742,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
1,AL200800000002,0.977610,0.006501,0.001889,-1.0,0.770744,-1.884142,0.0,2.0,40.696846,...,41.210404,19.947645,306.819742,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
2,AL200800000003,0.977610,0.026103,0.000842,-1.0,0.770744,-1.884142,0.0,2.0,NaN,...,41.210404,19.947645,306.819742,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
3,AL200800000004,0.977610,0.002900,0.000452,-1.0,0.770744,-1.884142,0.0,2.0,40.798931,...,41.210404,19.947645,306.819742,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
4,AL200800000005,0.977610,0.013001,0.000965,-1.0,0.770744,-1.884142,0.0,2.0,NaN,...,41.210404,19.947645,306.819742,4.984549,25.059406,24.434744,30.633723,1.753384,71.819921,16.425095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121881,ZW201500000396,0.000880,0.148215,0.205285,312.0,0.255685,5.115858,1.0,2.0,-17.915288,...,-18.496722,29.793360,303.011158,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275
121882,ZW201500000397,0.000098,0.144814,0.205285,559.0,0.422864,5.115858,0.0,2.0,-18.379501,...,-18.496722,29.793360,303.011158,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275
121883,ZW201500000398,0.000391,0.118212,0.205285,579.0,0.429625,5.115858,0.0,2.0,-16.660612,...,-18.496722,29.793360,303.011158,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275
121884,ZW201500000399,0.000880,0.141614,0.205285,312.0,0.255685,5.115858,1.0,2.0,NaN,...,-18.496722,29.793360,303.011158,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275
121885,ZW201500000400,0.000293,0.141314,0.205285,578.0,0.429010,5.115858,0.0,2.0,-17.859114,...,-18.496722,29.793360,303.011158,5.571827,23.719336,22.992242,17.691171,6.484954,75.459806,30.248275

In [ ]:
merged_vals.isnull().sum()

DHSID                                 0
ADM1DHS_x                           900
ALT_DEM_x                           900
ALT_GPS_x                           900
ADM1NAME_x                          900
DHSREGNA_x                          900
DHSYEAR_x_x                         900
URBAN_RURA_x_x                      900
SOURCE_x                            900
LATNUM_y_x                        19846
LONGNUM_y_x                       19846
DHSCLUST_x_x                        900
DHSREGCO_x                          900
ID                                    0
Mean_BMI_x                        39884
Median_BMI_x                      39884
Unmet_Need_Rate_x                 21753
Under5_Mortality_Rate_x           49501
Skilled_Birth_Attendant_Rate_x    53222
Stunted_Rate_x                    78541
ADM1DHS_y                             0
ALT_DEM_y                             0
ALT_GPS_y                             0
ADM1NAME_y                            0
DHSREGNA_y                            0
DHSYEAR_x_y                           0
URBAN_RURA_x_y                        0
SOURCE_y                              0
LATNUM_y_y                          219
LONGNUM_y_y                         219
DHSCLUST_x_y                          0
DHSREGCO_y                            0
Mean_BMI_y                         5831
Median_BMI_y                       5831
Unmet_Need_Rate_y                   219
Under5_Mortality_Rate_y           28745
Skilled_Birth_Attendant_Rate_y    28745
Stunted_Rate_y                    32151
dtype: int64

In [ ]:
# Fill NA Values with country specific mean values

merged_vals.loc[merged_vals['ADM1DHS_x'].isnull(),'ADM1DHS_x'] = merged_vals['ADM1DHS_y']
merged_vals.loc[merged_vals['ALT_DEM_x'].isnull(),'ALT_DEM_x'] = merged_vals['ALT_DEM_y']
merged_vals.loc[merged_vals['ALT_GPS_x'].isnull(),'ALT_GPS_x'] = merged_vals['ALT_GPS_y']
merged_vals.loc[merged_vals['ADM1NAME_x'].isnull(),'ADM1NAME_x'] = merged_vals['ADM1NAME_y']
merged_vals.loc[merged_vals['LATNUM_y_x'].isnull(),'LATNUM_y_x'] = merged_vals['LATNUM_y_y']
merged_vals.loc[merged_vals['LONGNUM_y_x'].isnull(),'LONGNUM_y_x'] = merged_vals['LONGNUM_y_y']
merged_vals.loc[merged_vals['DHSCLUST_x_x'].isnull(),'DHSCLUST_x_x'] = merged_vals['DHSCLUST_x_y']
merged_vals.loc[merged_vals['DHSYEAR_x_x'].isnull(),'DHSYEAR_x_x'] = merged_vals['DHSYEAR_x_y']
merged_vals.loc[merged_vals['DHSREGCO_x'].isnull(),'DHSREGCO_x'] = merged_vals['DHSREGCO_y']
merged_vals.loc[merged_vals['SOURCE_x'].isnull(),'SOURCE_x'] = merged_vals['SOURCE_y']
merged_vals.loc[merged_vals['URBAN_RURA_x_x'].isnull(),'URBAN_RURA_x_x'] = merged_vals['URBAN_RURA_x_y']
merged_vals.loc[merged_vals['Mean_BMI_x'].isnull(),'Mean_BMI_x'] = merged_vals['Mean_BMI_y']
merged_vals.loc[merged_vals['Median_BMI_x'].isnull(),'Median_BMI_x'] = merged_vals['Median_BMI_y']
merged_vals.loc[merged_vals['Unmet_Need_Rate_x'].isnull(),'Unmet_Need_Rate_x'] = merged_vals['Unmet_Need_Rate_y']
merged_vals.loc[merged_vals['Under5_Mortality_Rate_x'].isnull(),'Under5_Mortality_Rate_x'] = merged_vals['Under5_Mortality_Rate_y']
merged_vals.loc[merged_vals['Skilled_Birth_Attendant_Rate_x'].isnull(),'Skilled_Birth_Attendant_Rate_x'] = merged_vals['Skilled_Birth_Attendant_Rate_y']
merged_vals.loc[merged_vals['Stunted_Rate_x'].isnull(),'Stunted_Rate_x'] = merged_vals['Stunted_Rate_y']

In [ ]:
merged_vals['ID']= merged_vals['ID'].astype('category')
merged_vals['ID'] = merged_vals['ID'].cat.codes
merged_vals[['ID']]

        ID
0        0
1        0
2        0
3        0
4        0
...     ..
121881  59
121882  59
121883  59
121884  59
121885  59

[121886 rows x 1 columns]

In [ ]:
merge_df = merged_vals[["DHSID",	"ADM1DHS_x",	"ALT_DEM_x",	"ALT_GPS_x", "ADM1NAME_x",	"LATNUM_y_x",	"LONGNUM_y_x", "DHSYEAR_x_x", "DHSREGNA_x", 'SOURCE_x', "URBAN_RURA_x_x", "ID",	"DHSCLUST_x_x", "DHSREGCO_x", "Mean_BMI_x",
            "Median_BMI_x", "Unmet_Need_Rate_x", "Under5_Mortality_Rate_x", "Skilled_Birth_Attendant_Rate_x", "Stunted_Rate_x"]]
# Calculate the mean of each column
column_means = merge_df.mean()

# Replace NaN values with column means
df_filled = merge_df.fillna(column_means)

<ipython-input-37-99df01e58422>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  column_means = merge_df.mean()

In [ ]:
df_filled.isnull().sum()

DHSID                             0
ADM1DHS_x                         0
ALT_DEM_x                         0
ALT_GPS_x                         0
ADM1NAME_x                        0
LATNUM_y_x                        0
LONGNUM_y_x                       0
DHSYEAR_x_x                       0
DHSREGNA_x                        0
SOURCE_x                          0
URBAN_RURA_x_x                    0
ID                                0
DHSCLUST_x_x                      0
DHSREGCO_x                        0
Mean_BMI_x                        0
Median_BMI_x                      0
Unmet_Need_Rate_x                 0
Under5_Mortality_Rate_x           0
Skilled_Birth_Attendant_Rate_x    0
Stunted_Rate_x                    0
dtype: int64

In [ ]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# map = merge_df.corr()
# # Create the heatmap using the `heatmap` function of Seaborn
# sns.heatmap(map, cmap='coolwarm', annot=True)

# # Display the heatmap using the `show` method of the `pyplot` module from matplotlib.
# plt.show()

In [ ]:
df_filled.head()

In [ ]:
df_filled.set_index("DHSID",inplace=True)

In [ ]:
df_filled.isnull().sum()
# df_filled = df_filled.T.drop_duplicates().T
# df_filled[['DHSYEAR_x_x']]

In [ ]:
df_filled.rename(columns = {'ADM1DHS_x':'ADM1DHS','ALT_DEM_x':'ALT_DEM',"ALT_GPS_x":"ALT_GPS", "ADM1NAME_x":"ADM1NAME", "LATNUM_y_x":"LATNUM_y", "LONGNUM_y_x":"LONGNUM_y",
                            "SOURCE_x":"SOURCE", "DHSYEAR_x_x":"DHSYEAR", "DHSCLUST_x_x":"DHSCLUST", "URBAN_RURA_x_x":"URBAN_RURA", "DHSREGNA_x":"DHSREGNA", "DHSREGCO_x":"DHSREGCO", "Mean_BMI_x":"Mean_BMI", "Median_BMI_x":"Median_BMI",
                            "Unmet_Need_Rate_x":"Unmet_Need_Rate", "Under5_Mortality_Rate_x":"Under5_Mortality_Rate",
                            "Skilled_Birth_Attendant_Rate_x":"Skilled_Birth_Attendant_Rate", "Stunted_Rate_x":"Stunted_Rate"}, inplace = True)
df_filled.isnull().sum()

In [ ]:
df_filled.to_csv("/content/drive/MyDrive/Stanford Predictions/df_filled.csv",index=True)

In [ ]:
print(df_filled.columns)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
X=df_filled[['ADM1DHS', 'ALT_DEM', 'ALT_GPS', 'ADM1NAME', 'LATNUM_y', 'LONGNUM_y','DHSYEAR', 'DHSCLUST', 'DHSREGNA', 'SOURCE', 'DHSREGCO', 'URBAN_RURA', 'ID']]
# enc = OneHotEncoder(handle_unknown='ignore')
# enc.fit(X)
Y=df_filled[["Mean_BMI","Median_BMI",'Unmet_Need_Rate',"Under5_Mortality_Rate","Skilled_Birth_Attendant_Rate" ,"Stunted_Rate"]]

In [ ]:
# Coordinates = X['LATNUM_y', 'LONGNUM_y']
# Coordinates
X.isnull().sum()

ADM1DHS       0
ALT_DEM       0
ALT_GPS       0
ADM1NAME      0
LATNUM_y      0
LONGNUM_y     0
DHSYEAR       0
DHSCLUST      0
DHSREGNA      0
SOURCE        0
DHSREGCO      0
URBAN_RURA    0
ID            0
dtype: int64

In [ ]:
# Mosaiks file that includes mosaiks data based on the average lat and long of a country based on the country specific code
# https://siml.berkeley.edu/portal/file_query/ (link for acces to mosaiks data based on lat and long values)
# Manually edited file in Sheets as there were lots of missing data

mosaiks=pd.read_csv("/content/drive/MyDrive/Stanford Predictions/Mosaiks.csv")
# , sep=r'\s*,\s*',header=0, encoding='ascii', engine='python'
mosaiks

In [ ]:
# mosaiks['ID'] = mosaiks["DHSID"].str.slice(0, 2)
mosaiks['ID']= mosaiks['ID'].astype('category')
mosaiks['ID'] = mosaiks['ID'].cat.codes
mosaiks[['ID']]

In [ ]:
# merge the mosaiks database

new_X = X.merge(mosaiks, on='ID', how='outer')
new_X

In [ ]:
new_X.drop(["Lat", "Lon"],axis = 1, inplace = True)
minsce = new_X.mean()

# Replace NaN values with column means
new_X = new_X.fillna(minsce)
new_X.isnull().sum()

In [ ]:
new_X['CS_URBAN_RURA'] = (new_X['ID']+1)*((new_X['URBAN_RURA']*2)-1)
new_X.isnull().sum()

In [ ]:
new_X.to_csv("/content/drive/MyDrive/Stanford Predictions/new_X.csv",index=True) # save the training dataset
Y.to_csv("/content/drive/MyDrive/Stanford Predictions/Y.csv",index=True)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(new_X, Y, test_size=0.2, random_state=42)

In [ ]:
X.isnull().sum()

In [ ]:
# coordinates.to_csv("/content/drive/MyDrive/Stanford Predictions/coordinates.csv",index=True)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Create an instance of the model
model = RandomForestRegressor(n_estimators = 300, max_depth = 20, min_samples_split = 4, min_samples_leaf = 4, oob_score=True)
# Fit the model on the training data
model.fit(new_X, Y)

RandomForestRegressor(max_depth=20, min_samples_leaf=4, min_samples_split=4,
                      n_estimators=300, oob_score=True)

Below block is Testing and debugging

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

In [ ]:
predictions= pd.DataFrame(y_pred,columns=["Mean_BMI", "Median_BMI", "Unmet_Need_Rate", "Under5_Mortality_Rate", "Skilled_Birth_Attendant_Rate", "Stunted_Rate"])

In [ ]:
predictions

In [ ]:
predictions.set_index(Y_test.index, inplace=True)

In [ ]:
predictions

Real Testing Starts

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

# Assuming y_test contains the true labels and predictions contains the predicted labels
r2 = r2_score(Y_test, predictions)
rmse = np.sqrt(mean_squared_error(Y_test, predictions))

print("R-squared:", r2)
print("RMSE:", rmse)

R-squared: 0.7773653740846921
RMSE: 7.877039781519336

In [ ]:
Submission=pd.read_csv("/content/drive/MyDrive/sample submission.csv")

In [ ]:
Submission

In [ ]:
df_filled.columns

Index(['ADM1DHS', 'ALT_DEM', 'ALT_GPS', 'ADM1NAME', 'LATNUM_y', 'LONGNUM_y',
       'DHSYEAR', 'DHSREGNA', 'SOURCE', 'URBAN_RURA', 'ID', 'DHSCLUST',
       'DHSREGCO', 'Mean_BMI', 'Median_BMI', 'Unmet_Need_Rate',
       'Under5_Mortality_Rate', 'Skilled_Birth_Attendant_Rate',
       'Stunted_Rate'],
      dtype='object')

In [ ]:
Big_X=df[['ADM1DHS', 'ALT_DEM', 'ALT_GPS', 'ADM1NAME', 'LATNUM', 'LONGNUM', 'DHSYEAR', 'DHSCLUST', 'DHSREGNA', 'DHSREGCO', 'SOURCE', 'URBAN_RURA']]
Big_X.set_index(df['DHSID'],inplace=True)
Big_X.reset_index(inplace=True)
Big_X

,DHSID,ADM1DHS,ALT_DEM,ALT_GPS,ADM1NAME,LATNUM,LONGNUM,DHSYEAR,DHSCLUST,DHSREGNA,DHSREGCO,SOURCE,URBAN_RURA
0,AL200800000001,0.977610,0.004500,0.000801,-1,40.822650,19.838322,-1.884142,1,0.770744,2,2,0
1,AL200800000002,0.977610,0.006501,0.001889,-1,40.696846,20.007555,-1.884142,2,0.770744,2,2,0
2,AL200800000003,0.977610,0.026103,0.000842,-1,40.750040,19.974262,-1.884142,3,0.770744,2,2,0
3,AL200800000004,0.977610,0.002900,0.000452,-1,40.798930,19.863338,-1.884142,4,0.770744,2,2,0
4,AL200800000005,0.977610,0.013001,0.000965,-1,40.746124,19.843885,-1.884142,5,0.770744,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120979,ZW201500000396,0.000880,0.148215,0.205285,312,-17.915289,31.156115,5.115858,396,0.255685,9,2,1
120980,ZW201500000397,0.000098,0.144814,0.205285,559,-18.379501,31.872288,5.115858,397,0.422864,1,2,0
120981,ZW201500000398,0.000391,0.118212,0.205285,579,-16.660612,29.850649,5.115858,398,0.429625,4,2,0
120982,ZW201500000399,0.000880,0.141614,0.205285,312,-17.914251,30.956976,5.115858,399,0.255685,9,2,1
120983,ZW201500000400,0.000293,0.141314,0.205285,578,-17.859114,31.797626,5.115858,400,0.429010,3,2,0

In [ ]:
# Create a country specific code

Big_X['ID'] = Big_X["DHSID"].str.slice(0, 2)
Big_X

In [ ]:
Big_X['ID']= Big_X['ID'].astype('category')
Big_X['ID'] = Big_X['ID'].cat.codes
Big_X

In [ ]:
# Big_X.set_index('DHSID',inplace = True)
Big_X = Big_X.drop_duplicates(subset='DHSID', keep='first')
Big_X

In [ ]:
Big_X.set_index('DHSID',inplace = True)

In [ ]:
# merge the prediction X values and the gee features

Subm_x = Big_X.merge(Submission, on='DHSID', how='inner')
Subm_x

In [ ]:
X_Final = Subm_x[['DHSID', 'ADM1DHS', 'ALT_DEM', 'ALT_GPS', 'ADM1NAME', 'LATNUM', 'LONGNUM', 'DHSYEAR', 'DHSCLUST', 'DHSREGNA', 'SOURCE', 'DHSREGCO', 'URBAN_RURA', 'ID']]
Y_Final = Subm_x[["DHSID", 'Mean_BMI', 'Median_BMI', 'Unmet_Need_Rate', 'Under5_Mortality_Rate', 'Skilled_Birth_Attendant_Rate', 'Stunted_Rate']]
X_Final.set_index("DHSID",inplace=True)
Y_Final.set_index("DHSID",inplace=True)
X_Final

In [ ]:
X_Final.rename(columns = {'LATNUM':'LATNUM_y','LONGNUM':'LONGNUM_y'}, inplace = True)
X_Final

<ipython-input-228-a1c4886becf3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_Final.rename(columns = {'LATNUM':'LATNUM_y','LONGNUM':'LONGNUM_y'}, inplace = True)

,ADM1DHS,ALT_DEM,ALT_GPS,ADM1NAME,LATNUM_y,LONGNUM_y,DHSYEAR,DHSCLUST,DHSREGNA,SOURCE,DHSREGCO,URBAN_RURA,ID
DHSID,,,,,,,,,,,,,
AL200800000003,0.977610,0.026103,0.000842,-1,40.750040,19.974262,-1.884142,3,0.770744,2,2,0,0
AL200800000005,0.977610,0.013001,0.000965,-1,40.746124,19.843885,-1.884142,5,0.770744,2,2,0,0
AL200800000007,0.977610,0.025903,0.001478,-1,40.701607,19.989952,-1.884142,7,0.770744,2,2,1,0
AL200800000008,0.977610,0.043304,0.001273,-1,40.695984,19.965063,-1.884142,8,0.770744,2,2,1,0
AL200800000009,0.977610,0.005901,0.001232,-1,40.698685,19.981623,-1.884142,9,0.770744,2,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZW201500000382,0.000782,0.090909,0.205285,580,-19.939451,31.822948,5.115858,382,0.430240,2,8,0,59
ZW201500000383,0.000489,0.120312,0.205285,583,-19.851952,28.240479,5.115858,383,0.430854,2,5,0,59
ZW201500000386,0.000587,0.049405,0.205285,584,-22.126260,29.639608,5.115858,386,0.431469,2,6,0,59
ZW201500000390,0.000880,0.146315,0.205285,312,-17.878082,31.033348,5.115858,390,0.255685,2,9,1,59
ZW201500000399,0.000880,0.141614,0.205285,312,-17.914251,30.956976,5.115858,399,0.255685,2,9,1,59

In [ ]:
new_X_Final = X_Final.merge(mosaiks, on='ID')
new_X_Final

In [ ]:
new_X_Final.drop(["Lat", "Lon"],axis = 1, inplace = True)
minsce = new_X_Final.mean()

# Replace NaN values with column means
new_X_Final = new_X_Final.fillna(minsce)
new_X_Final

In [ ]:
new_X_Final['CS_URBAN_RURA'] = (new_X_Final['ID']+1)*(new_X_Final['URBAN_RURA']+1)
new_X_Final.isnull().sum()

In [ ]:
pred_final = model.predict(new_X_Final)

In [ ]:
Finality = pd.DataFrame(pred_final,columns=["Mean_BMI", "Median_BMI", "Unmet_Need_Rate", "Under5_Mortality_Rate", "Skilled_Birth_Attendant_Rate", "Stunted_Rate"])
Finality.set_index(Y_Final.index, inplace=True)
Finality

In [ ]:
k = Submission["DHSID"]
Submission.drop(['DHSID'], axis=1,inplace = True)
Submission.set_index(k, inplace=True)
Submission.loc[:] = np.nan
# Submission = np.nan
Submission

In [ ]:
Submission.reset_index(inplace=True)
Finality.reset_index(inplace=True)
missing_vals = Submission.merge(Finality, on = "DHSID", how = "outer")
missing_vals

In [ ]:
missing_vals.drop(["Mean_BMI_x", "Median_BMI_x", "Unmet_Need_Rate_x", "Under5_Mortality_Rate_x", "Skilled_Birth_Attendant_Rate_x", "Stunted_Rate_x"], axis=1,inplace = True)
missing_vals

In [ ]:
missing_vals.isna().sum()

DHSID                              0
Mean_BMI_y                        25
Median_BMI_y                      25
Unmet_Need_Rate_y                 25
Under5_Mortality_Rate_y           25
Skilled_Birth_Attendant_Rate_y    25
Stunted_Rate_y                    25
dtype: int64

In [ ]:
column_means = missing_vals.mean()

# Replace NaN values with column means
final_p= missing_vals.fillna(column_means)
final_p

In [ ]:
final_p.rename(columns = {"Mean_BMI_y":"Mean_BMI","Median_BMI_y":'Median_BMI',"Unmet_Need_Rate_y":"Unmet_Need_Rate","Under5_Mortality_Rate_y":"Under5_Mortality_Rate","Skilled_Birth_Attendant_Rate_y":"Skilled_Birth_Attendant_Rate","Stunted_Rate_y":"Stunted_Rate"}, inplace = True)
# final_p.set_index(final_p["DHSID"], inplace = True)
final_p

In [ ]:
# final_p.drop(['DHSID'], inplace = True)
# final_p.isna().sum()
final_p

In [ ]:
final_p.to_csv("/content/drive/MyDrive/Stanford Predictions/finalp29.csv",index=True)